Today's topics:
* `numpy` arrays, a variable that holds many numbers
* elementwise arithmetic: `+`, `-`, `*`, `/`, `**`
* scalar broadcasting

# One number isn't enough

Last class: `density = mass / volume` for one sample.

A real lab measures a batch. 10 samples, 10 masses, 10 volumes, 10 separate division lines?

And 10 is small:
* Tensile frame: force at hundreds of time steps per coupon
* XRD scan: intensity at thousands of diffraction angles
* EDS line scan: composition at hundreds of positions

Instrument exports become arrays. Arrays are the default, not a special case.

<img src="https://upload.wikimedia.org/wikipedia/commons/6/6f/Al_tensile_test.jpg" alt="Tensile test of aluminum alloy" height=200/>

(Sigmund, [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Al_tensile_test.jpg), [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/))



# Meet `np.array`

[NumPy](https://numpy.org/) is the standard library for numerical Python. Convention: `import numpy as np`

In [1]:
import numpy as np

10 aluminum-alloy bar-stock samples (synthetic teaching data):

To make an array, write `np.array([...])` with your values between the square brackets, separated by commas.

In [2]:
mass = np.array([27.0, 41.6, 13.5, 54.2, 20.8, 33.9, 47.3, 16.9, 60.7, 24.5])
print(mass)

[27.  41.6 13.5 54.2 20.8 33.9 47.3 16.9 60.7 24.5]


In [3]:
volume = np.array([10.0, 15.0, 5.0, 20.0, 8.0, 12.0, 17.5, 6.5, 22.0, 9.0])
print(volume)

[10.  15.   5.  20.   8.  12.  17.5  6.5 22.   9. ]


In [4]:
print(type(mass))
print(len(mass))

<class 'numpy.ndarray'>
10


`ndarray` = "n-dimensional array." Today: 1-D only.

> **Read more:** [Python Data Science Handbook — Introduction to NumPy](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)

## Dimensionality in materials data



Materials data comes at different scales of complexity:

* **Scalar** - a single number (atomic number of iron: `26`, density of copper: `8.96`)
* **Vector** - an ordered sequence (the `mass` array above holds 10 measurements from one experiment)


*What does the data from a test like this actually look like?*

Here are 12 points from the elastic region of a published stress-strain curve
([Zheng et al., Science 344, 2014](https://doi.org/10.1126/science.1252291)):

In [5]:
strain = np.array([0.002, 0.004, 0.006, 0.008, 0.010, 0.012, 0.014, 0.016, 0.018, 0.020, 0.022, 0.024])
stress_MPa = np.array([1.2, 2.5, 3.7, 5.0, 6.2, 7.4, 8.7, 10.0, 11.2, 12.4, 13.7, 15.0])
print(strain)
print(stress_MPa)

[0.002 0.004 0.006 0.008 0.01  0.012 0.014 0.016 0.018 0.02  0.022 0.024]
[ 1.2  2.5  3.7  5.   6.2  7.4  8.7 10.  11.2 12.4 13.7 15. ]


Two parallel arrays, 12 entries each. The elastic modulus is the slope:

In [6]:
modulus = stress_MPa / strain
print(modulus)
print(modulus)

[600.         625.         616.66666667 625.         620.
 616.66666667 621.42857143 625.         622.22222222 620.
 622.72727273 625.        ]
[600.         625.         616.66666667 625.         620.
 616.66666667 621.42857143 625.         622.22222222 620.
 622.72727273 625.        ]


One line of elementwise division, 12 modulus estimates.

# Elementwise arithmetic

*All 10 densities in one line:*

In [7]:
density = mass / volume
print(density)

[2.7        2.77333333 2.7        2.71       2.6        2.825
 2.70285714 2.6        2.75909091 2.72222222]


In [8]:
print(type(density))
print(len(density))

<class 'numpy.ndarray'>
10


NumPy divided entry by entry: first mass with first volume, second with second, and so on.

The two arrays are **parallel**: index i refers to the same specimen in both.
Shuffled order? Division still runs, densities come out wrong. NumPy rejects
incompatible lengths but cannot check specimen order, units, or physical meaning.

## Broadcasting: adding a scalar to every entry

In [9]:
print(mass + 0.5)

[27.5 42.1 14.  54.7 21.3 34.4 47.8 17.4 61.2 25. ]


Same as $\vec{m} + 0.5 = (m_1 + 0.5,\ m_2 + 0.5,\ \ldots)$

Works with any operator:

In [10]:
print(mass - 2.0)
print((mass + 0.5) / volume)

[25.  39.6 11.5 52.2 18.8 31.9 45.3 14.9 58.7 22.5]
[2.75       2.80666667 2.8        2.735      2.6625     2.86666667
 2.73142857 2.67692308 2.78181818 2.77777778]


### [Check your understanding]

In the code cell below, convert `density` from g/cm³ to kg/m³ (multiply by 1000). Print the result:

## Combining two arrays

In [11]:
print(mass + volume)
print(mass * volume)

[37.  56.6 18.5 74.2 28.8 45.9 64.8 23.4 82.7 33.5]
[ 270.    624.     67.5  1084.    166.4   406.8   827.75  109.85 1335.4
  220.5 ]


Entry-by-entry: first mass with first volume, second with second, and so on.

NumPy checks shapes, not units. `mass + volume` (g + cm³) is physically meaningless but runs fine.

## Powers with `**`

In [12]:
side_length = np.array([2.0, 3.5, 1.0, 4.2, 2.8])
cube_volume = side_length ** 3
print(cube_volume)

[ 8.    42.875  1.    74.088 21.952]


<img src="https://imgs.xkcd.com/comics/efficiency.png" alt="XKCD comic #1445, Efficiency" height=350/>

(Randall Munroe, [xkcd #1445](https://xkcd.com/1445/), [CC BY-NC 2.5](https://creativecommons.org/licenses/by-nc/2.5/))

## When shapes don't match

In [13]:
# EXPECTED-ERROR: this cell fails on purpose -- see the surrounding text
wrong_size = np.array([1.0, 2.0, 3.0])
print(mass + wrong_size)

ValueError: operands could not be broadcast together with shapes (10,) (3,) 

`ValueError: shapes (10,) (3,)`, can't line up 10 entries with 3. Check `len()` on both arrays.

> **Read more:** [PDSH — Computation on Arrays: Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

In [14]:
print(len(mass), len(wrong_size))

10 3


# Guided practice: screening a batch

Pure aluminum: about 2.70 g/cm³. Values far from that suggest a mislabeled
sample or measurement error.

In [15]:
print(np.min(density), np.max(density))

2.5999999999999996 2.8249999999999997


Range: 2.60 to 2.83 g/cm³, all plausible for aluminum alloys. Quick batch screening
like this is one of the first things you do with lab data.

Spot-check: sample 0 should be 27.0 / 10.0 = 2.7.

`[0]` grabs the first entry, `[1]` the second, and so on.

In [16]:
print(mass[0], volume[0], density[0])

27.0 10.0 2.7


## Unit conversion is just broadcasting

g/cm³ → kg/m³: multiply by 1000

In [17]:
density_SI = density * 1000
print(density_SI)

[2700.         2773.33333333 2700.         2710.         2600.
 2825.         2702.85714286 2600.         2759.09090909 2722.22222222]


In [18]:
print(f'Highest density: {np.max(density):.2f} g/cm^3, or {np.max(density_SI):.1f} kg/m^3.')

Highest density: 2.82 g/cm^3, or 2825.0 kg/m^3.


### [Check your understanding]

A tensile test on 8 coupons:

```
applied_force      = [4200, 5600, 3100, 7400, 6000, 4800, 8900, 5300]   # N
cross_section_area = [20.0, 25.0, 15.5, 30.0, 28.0, 22.0, 35.0, 24.0]  # mm^2
```

In the code cell below:
* Build both as `np.array`
* Compute `stress = applied_force / cross_section_area` (units: MPa)
* Convert to ksi: `stress_ksi = stress * 0.145`
* Print `stress_ksi` and identify the highest-stress coupon

## Hands-on: are lead atoms really big?

Pure metals span a wide range of density. Below are 14 common structural metals
with their atomic mass and handbook density at room temperature.

In [19]:
metals = np.array(['Cu','Ni','Al','Zn','Pb','Sc','Ti','V','Cr','Ga','Sn','Co','In','Fe'])
atomic_mass = np.array([63.546, 58.693, 26.981, 65.38, 207.2, 44.955, 47.867, 50.942, 51.996, 69.723, 118.71, 58.933, 114.818, 55.845])
density_handbook = np.array([8.96, 8.908, 2.70, 7.14, 11.34, 2.985, 4.506, 6.11, 7.19, 5.91, 7.265, 8.90, 7.31, 7.874])

print(metals)
print(atomic_mass)
print(density_handbook)

['Cu' 'Ni' 'Al' 'Zn' 'Pb' 'Sc' 'Ti' 'V' 'Cr' 'Ga' 'Sn' 'Co' 'In' 'Fe']
[ 63.546  58.693  26.981  65.38  207.2    44.955  47.867  50.942  51.996
  69.723 118.71   58.933 114.818  55.845]
[ 8.96   8.908  2.7    7.14  11.34   2.985  4.506  6.11   7.19   5.91
  7.265  8.9    7.31   7.874]


Lead's density, 11.34 g/cm³, is by far the highest in this list. Does that mean a
lead atom takes up more space than the others?

Molar volume answers that directly: the volume occupied by one mole of atoms,
$V_m = A / \rho$ (cm³/mol). In the code cell below, compute `molar_volume` from
`atomic_mass` and `density_handbook`, then print it.

Use `np.min` and `np.max` to find the smallest and largest molar volume. Compare
the ratio (max / min) for `density_handbook` to the ratio for `molar_volume`.

Density spans about 4.2x across these 14 metals, but molar volume spans only about
2.8x. Lead's high density comes mostly from its large atomic mass, 207.2 g/mol,
more than 3x copper's, not from unusually large atoms.