Today's topics:
* indexing, pulling one entry out of an array
* slicing, pulling a range of entries
* fancy indexing, arbitrary positions
* 2D arrays, `.shape`, and the `axis` idea

# Setup: 20 elements

The periodic table: one of the oldest datasets in materials science.

<img src="https://upload.wikimedia.org/wikipedia/commons/2/2e/Simple_Periodic_Table_Chart-en.svg" alt="Periodic table" height=250/>

([Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Simple_Periodic_Table_Chart-en.svg), public domain)

Every element has dozens of measured properties. Today: indexing and
slicing on the first 20.

In [1]:
import numpy as np

elements = np.array(['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne',
                      'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca'])
melting_K = np.array([14.01, 0.95, 453.65, 1560, 2349, 3823, 63.15, 54.36,
                       53.53, 24.56, 370.87, 923, 933.47, 1687, 317.3,
                       388.36, 171.6, 83.80, 336.53, 1115])
print(elements)
print(melting_K)

['H' 'He' 'Li' 'Be' 'B' 'C' 'N' 'O' 'F' 'Ne' 'Na' 'Mg' 'Al' 'Si' 'P' 'S'
 'Cl' 'Ar' 'K' 'Ca']
[1.4010e+01 9.5000e-01 4.5365e+02 1.5600e+03 2.3490e+03 3.8230e+03
 6.3150e+01 5.4360e+01 5.3530e+01 2.4560e+01 3.7087e+02 9.2300e+02
 9.3347e+02 1.6870e+03 3.1730e+02 3.8836e+02 1.7160e+02 8.3800e+01
 3.3653e+02 1.1150e+03]


These arrays are **parallel**: `elements[i]` and `melting_K[i]` describe the same element.

In [2]:
print(f'index 0: {elements[0]}  ({melting_K[0]:.2f} K)')
print(f'index 1: {elements[1]}  ({melting_K[1]:.2f} K)')
print(f'index 2: {elements[2]}  ({melting_K[2]:.2f} K)')
print(f'index 3: {elements[3]}  ({melting_K[3]:.2f} K)')

index 0: H  (14.01 K)
index 1: He  (0.95 K)
index 2: Li  (453.65 K)
index 3: Be  (1560.00 K)


# Zero-based indexing

*What is carbon's melting point?*

Carbon is the 6th element listed → index **5** (counting starts at 0):

In [3]:
print(melting_K[6])   # this is nitrogen, not carbon!

63.15


In [4]:
print(elements[0])
print(melting_K[5])
print(elements[5])

H
3823.0
C


Rule: `array[i]` = the `(i+1)`-th item. Valid indices: `0` to `len-1`.

> **Read more:** [PDSH — The Basics of NumPy Arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html)

In [5]:
print(len(elements))

20


*What if we go out of bounds?*

In [6]:
# EXPECTED-ERROR: this cell fails on purpose -- see the surrounding text
print(melting_K[20])

IndexError: index 20 is out of bounds for axis 0 with size 20

`IndexError`, index 20 doesn't exist in a 20-element array (0-19).

## Negative indexing

`-1` = last item, `-2` = second-to-last:

In [7]:
print(elements[-1])
print(melting_K[-1])
print(elements[-2])

Ca
1115.0
K


In [8]:
print(melting_K[19])
print(melting_K[-1])

1115.0
1115.0


Same value. Index 19 and index -1 both reach the last element.

### [Check your understanding]

In the code cell below, print the symbol and melting point of phosphorus (count carefully!):

# Slicing: a range of entries

`array[start:stop]` grabs from `start` up to but **not including** `stop`:

Period 2 (Li through Ne) and period 3 (Na through Ar):

In [9]:
print(elements[2:10])
print(melting_K[2:10])

['Li' 'Be' 'B' 'C' 'N' 'O' 'F' 'Ne']
[ 453.65 1560.   2349.   3823.     63.15   54.36   53.53   24.56]


In [10]:
print(elements[10:18])
print(melting_K[10:18])

['Na' 'Mg' 'Al' 'Si' 'P' 'S' 'Cl' 'Ar']
[ 370.87  923.    933.47 1687.    317.3   388.36  171.6    83.8 ]


Melting points rise toward strongly bonded elements (C: 3823 K, Si: 1687 K),
then drop at the noble gases. Not perfectly smooth, but the pattern repeats.
Period boundaries make better slices than arbitrary splits like `[0:10]`.

Omit `start` or `stop` to mean "from the beginning" or "to the end":

In [11]:
print(elements[:5])
print(elements[15:])

['H' 'He' 'Li' 'Be' 'B']
['S' 'Cl' 'Ar' 'K' 'Ca']


With a **step**: `array[start:stop:step]`

In [12]:
print(elements[::2])     # every other, starting from 0
print(elements[1::2])    # every other, starting from 1

['H' 'Li' 'B' 'N' 'F' 'Na' 'Al' 'P' 'Cl' 'K']
['He' 'Be' 'C' 'O' 'Ne' 'Mg' 'Si' 'S' 'Ar' 'Ca']


In [13]:
print(elements[-5:])     # last five

['S' 'Cl' 'Ar' 'K' 'Ca']


# Fancy indexing: arbitrary positions

The alkali metals Li, Na, K are at indices 2, 10, 18, not a contiguous range.
Use a **collection of indices** inside square brackets to select several positions at once:

In [14]:
alkali_idx = [2, 10, 18]
print(elements[alkali_idx])
print(melting_K[alkali_idx])

['Li' 'Na' 'K']
[453.65 370.87 336.53]


454, 371, 337 K: melting point decreases down the group.

*Why?* Atomic radius increases (Li < Na < K), so the metallic bond weakens.
Students in intro MatSE see this same trend. Here it falls out of a fancy-index
selection: a chemical family in the table is a noncontiguous set of array indices.

The index spacing (2, 10, 18 differ by 8) reflects period lengths. This array is
ordered by atomic number, so index = atomic number - 1. Position encodes identity
only because the ordering convention is preserved.

Fancy indexing is a NumPy feature. It does not work on every kind of Python container.

> **Read more:** [PDSH — Fancy Indexing](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html)

### [Check your understanding]

In the code cell below:
* Print the last three elements using a slice
* Print H, O, and Ca using fancy indexing

# 2D arrays

*What if each element has multiple properties?*

Stack two 1-D arrays into one 2-D array:

In [15]:
radius_pm = np.array([25, 31, 145, 105, 85, 70, 65, 60, 50, 38,
                       180, 150, 125, 110, 100, 100, 100, 71, 220, 180])
properties = np.array([melting_K, radius_pm])
print(properties)

[[1.4010e+01 9.5000e-01 4.5365e+02 1.5600e+03 2.3490e+03 3.8230e+03
  6.3150e+01 5.4360e+01 5.3530e+01 2.4560e+01 3.7087e+02 9.2300e+02
  9.3347e+02 1.6870e+03 3.1730e+02 3.8836e+02 1.7160e+02 8.3800e+01
  3.3653e+02 1.1150e+03]
 [2.5000e+01 3.1000e+01 1.4500e+02 1.0500e+02 8.5000e+01 7.0000e+01
  6.5000e+01 6.0000e+01 5.0000e+01 3.8000e+01 1.8000e+02 1.5000e+02
  1.2500e+02 1.1000e+02 1.0000e+02 1.0000e+02 1.0000e+02 7.1000e+01
  2.2000e+02 1.8000e+02]]


In [16]:
print(properties.shape)

(2, 20)


`(2, 20)` = 2 rows (properties), 20 columns (elements).

**Dimensionality:** a **matrix**, 2-D, rows x columns.

* L01: single numbers (scalars)
* L02: 1-D arrays of measurements (vectors)
* Now: a 2-D property table, two properties on 20 elements

Real materials datasets are exactly this shape: rows are properties or specimens,
columns are elements or measurements.

## 2D indexing: `array[row, col]`

In [17]:
print(properties[0, 5])    # row 0 (melting pt), col 5 (carbon)
print(properties[1, 5])    # row 1 (radius), col 5 (carbon)

3823.0
70.0


Grab an entire row or column with `:`:

In [18]:
print(properties[0, :])    # all melting points
print(properties[:, 5])    # both properties for carbon

[1.4010e+01 9.5000e-01 4.5365e+02 1.5600e+03 2.3490e+03 3.8230e+03
 6.3150e+01 5.4360e+01 5.3530e+01 2.4560e+01 3.7087e+02 9.2300e+02
 9.3347e+02 1.6870e+03 3.1730e+02 3.8836e+02 1.7160e+02 8.3800e+01
 3.3653e+02 1.1150e+03]
[3823.   70.]


## `axis` preview

`np.mean` computes an average. With a 2-D array,
you choose which direction to average over:

* `axis=0` - down the rows (across properties, for one element)
* `axis=1` - across columns (across elements, for one property)

In [19]:
print(np.mean(properties, axis=1))   # 2 values: avg melting pt, avg radius

[736.157 100.5  ]


In [20]:
print(np.mean(properties, axis=1).shape)   # 2 values (one per property)
print(np.mean(properties, axis=0).shape)   # 20 values (one per element)

(2,)
(20,)


`axis=1`: one average per property row (K stays K, pm stays pm).
`axis=0`: averages K with pm for each element, physically meaningless.
The shape permits either axis. Units determine which makes sense.

### [Check your understanding]

In the code cell below:
* Print the atomic radius of silicon using 2D indexing
* Print the full atomic-radius row using `:`
* Compute `np.mean(properties, axis=1)`, which number is the average melting point?

## Hands-on: crystal families by fancy index

The same 14 metals from last lecture, this time with melting point and Young's
modulus. Crystal structure groups elements into families with shared bonding
geometry, and often shared mechanical behavior.

In [21]:
metals = np.array(['Cu','Ni','Al','Zn','Pb','Sc','Ti','V','Cr','Ga','Sn','Co','In','Fe'])
melting_K = np.array([1358, 1728, 933, 693, 601, 1814, 1941, 2183, 2180, 303, 505, 1768, 430, 1811])
youngs_GPa = np.array([117, 200, 70, 108, 16, 74, 116, 128, 279, 9.8, 50, 209, 11, 211])

print(metals)
print(melting_K)
print(youngs_GPa)

['Cu' 'Ni' 'Al' 'Zn' 'Pb' 'Sc' 'Ti' 'V' 'Cr' 'Ga' 'Sn' 'Co' 'In' 'Fe']
[1358 1728  933  693  601 1814 1941 2183 2180  303  505 1768  430 1811]
[117.  200.   70.  108.   16.   74.  116.  128.  279.    9.8  50.  209.
  11.  211. ]


Crystal structure at room temperature, by index:

| family | metals (index) |
|---|---|
| FCC | Cu (0), Ni (1), Al (2), Pb (4) |
| HCP | Zn (3), Sc (5), Ti (6), Co (11) |
| BCC | V (7), Cr (8), Fe (13) |

Ga (9), Sn (10), and In (12) crystallize in other structures and are left out of
this comparison.

In the code cell below, use fancy indexing to build `fcc_idx`, `hcp_idx`, and
`bcc_idx` from the table above, then pull out `melting_K` and `youngs_GPa` for
each family.

Compute `np.mean` of melting point and Young's modulus for each family. Which
family has the highest average melting point? The highest average modulus?